# Generated by Django 4.1.3 on 2023-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield>'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
