# Generated by Django 4.1.3 on 2023-04-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_article_options_alter_article_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_created'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
