# Generated by Django 4.1.3 on 2023-03-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_image'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blogapp.article'),
        ),
    ]
