# Generated by Django 4.1.3 on 2023-04-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmodel_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
